/* GAMBLY — Comunidades */
(()=>{
 const API='/api',KEY='betsocial_v08_token';let token=localStorage.getItem(KEY)||sessionStorage.getItem(KEY),current=null,all=[];
 const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const api=async(path,opts={})=>{const h={'Content-Type':'application/json',...(opts.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(API+path,{...opts,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Falha na API');return d};
 const toast=v=>{const t=$('#toast');if(t){t.textContent=v;t.classList.add('show');clearTimeout(window.__communityToast);window.__communityToast=setTimeout(()=>t.classList.remove('show'),2600)}};
 const modal=$('#communitiesModal'),createModal=$('#createCommunityModal');
 function renderList(items=all){const q=($('#communitySearch')?.value||'').toLowerCase().trim();const list=items.filter(c=>!q||c.name.toLowerCase().includes(q)||String(c.description||'').toLowerCase().includes(q));$('#communityList').innerHTML=list.length?list.map(c=>`<button class="community-item ${current?.id===c.id?'active':''}" data-community-id="${esc(c.id)}"><b>${esc(c.name)}</b><small>${c.membersCount} membro(s) · ${c.settings?.joinMode==='approval'?'aprovação':'entrada automática'}</small></button>`).join(''):'<div class="empty-state">Nenhuma comunidade encontrada.</div>';document.querySelectorAll('[data-community-id]').forEach(b=>b.onclick=()=>load(b.dataset.communityId))}
 async function refresh(){try{const d=await api('/communities');all=d.communities||[];renderList();if(current){const c=all.find(x=>x.id===current.id);if(c)load(c.id)}}catch(e){toast(e.message)}}
 async function load(id){try{const d=await api('/communities/'+encodeURIComponent(id));current=d.community;renderList();render(d.community)}catch(e){toast(e.message)}}
 function render(c){
   const member=!!c.isMember, owner=c.ownerId===window.BetSocialCommunityUser?.id;
   const settings=c.settings||{};
   const action=!member?(c.pending?'<button class="publish-btn" disabled>Solicitação enviada</button>':`<button class="publish-btn" id="joinCommunity">${settings.joinMode==='approval'?'Solicitar entrada':'Entrar na comunidade'}</button>`):'';
   const posts=(c.posts||[]); const pending=(c.pendingMembers||[]); const pendingHtml=owner&&pending.length?`<div class="community-requests"><b>Solicitações de entrada (${pending.length})</b>${pending.map(u=>`<div><span>${esc(u.name)}</span><button type="button" data-approve-community="${esc(u.id)}">Aprovar</button></div>`).join('')}</div>`:'';
   $('#communityMain').innerHTML=`<div class="community-head"><div><div class="community-kicker">♧ COMUNIDADE</div><h3>${esc(c.name)}</h3><p>${esc(c.description||'Comunidade GAMBLY')}</p></div>${action}</div><div class="community-meta"><span>${c.membersCount||c.members?.length||0} membro(s)</span><span>${settings.joinMode==='approval'?'Entrada com aprovação':'Entrada automática'}</span><span>${settings.postingMode==='admin'?'Só administrador publica':'Todos podem publicar'}</span></div>${member?`<div class="community-composer"><textarea id="communityPostText" rows="2" placeholder="${settings.postingMode==='admin'&&!owner?'Somente o administrador pode publicar':'Compartilhe uma análise com a comunidade...'}" ${settings.postingMode==='admin'&&!owner?'disabled':''}></textarea><button id="communityPostBtn" type="button" ${settings.postingMode==='admin'&&!owner?'disabled':''}>Publicar</button></div>`:''}<div class="community-feed">${posts.length?posts.map(p=>`<article class="community-post"><div class="community-post-head"><span class="avatar avatar-xs avatar-purple">${esc((p.author||'?')[0].toUpperCase())}</span><div><b>${esc(p.author||'Membro')}</b><small>${new Date(p.createdAt).toLocaleDateString('pt-BR')}</small></div></div><p>${esc(p.text)}</p></article>`).join(''):'<div class="empty-state">Ainda não há publicações nesta comunidade.</div>'}</div>${owner?`<div class="community-admin"><b>Organização</b><small>Entrada: ${settings.joinMode==='approval'?'aprovação do administrador':'automática'} · Publicação: ${settings.postingMode==='admin'?'somente administrador':'todos'}</small></div>`:''}`;
   document.querySelectorAll('[data-approve-community]').forEach(b=>b.addEventListener('click',async()=>{try{await api('/communities/'+encodeURIComponent(c.id)+'/requests/'+encodeURIComponent(b.dataset.approveCommunity),{method:'POST'});toast('Solicitação aprovada.');await load(c.id)}catch(e){toast(e.message)}}));
   $('#joinCommunity')?.addEventListener('click',async()=>{try{const d=await api('/communities/'+encodeURIComponent(c.id)+'/join',{method:'POST'});toast(d.status==='pending'?'Solicitação enviada ao administrador.':'Você entrou na comunidade.');await refresh();await load(c.id)}catch(e){toast(e.message)}});
   $('#communityPostBtn')?.addEventListener('click',async()=>{const text=$('#communityPostText')?.value.trim();if(!text)return;try{await api('/communities/'+encodeURIComponent(c.id)+'/posts',{method:'POST',body:JSON.stringify({text})});toast('Publicação criada.');await load(c.id)}catch(e){toast(e.message)}});
 }
 function open(){modal?.classList.add('open');refresh()}
 $('#openCommunities')?.addEventListener('click',open);
 $('#createCommunity')?.addEventListener('click',()=>{createModal?.classList.add('open');$('#communityName')?.focus()});
 $('#communitySearch')?.addEventListener('input',()=>renderList());
 $('#createCommunityForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/communities',{method:'POST',body:JSON.stringify({name:$('#communityName').value.trim(),description:$('#communityDescription').value.trim(),joinMode:$('#communityJoinMode').value,postingMode:$('#communityPostingMode').value})});createModal.classList.remove('open');e.target.reset();toast('Comunidade criada.');await refresh();await load(d.community.id)}catch(err){toast(err.message)}});
 document.addEventListener('click',e=>{if(e.target.closest('[data-close-communities]')||e.target===modal)modal?.classList.remove('open');if(e.target.closest('[data-close-create-community]')||e.target===createModal)createModal?.classList.remove('open')});
 document.addEventListener('betsocial:auth',e=>{token=localStorage.getItem(KEY)||sessionStorage.getItem(KEY)||'';window.BetSocialCommunityUser=e.detail?.user||null});
 window.BetSocialCommunity={refresh,open}; (async()=>{try{const d=await api('/auth/me');window.BetSocialCommunityUser=d.user}catch{}})();
})();
