/* BetSocial v0.5 — API/backend integration */
(() => {
  const API='/api';
  const TOKEN_KEY='betsocial_v05_token';
  let token=localStorage.getItem(TOKEN_KEY);
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast=v=>{const t=$('#toast');if(t){t.textContent=v;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}};
  async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(API+path,{...opts,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Falha na API');return d}
  async function health(){try{await api('/health');setStatus(true)}catch(e){setStatus(false)}}
  function setStatus(on){let b=$('#backendStatus');if(!b)return;b.classList.toggle('online',on);b.classList.toggle('offline',!on);b.innerHTML=`<i></i>${on?'API online':'API offline'}`}
  function addStatus(){const host=$('.top-actions');if(host&&!$('#backendStatus')){const b=document.createElement('span');b.id='backendStatus';b.className='backend-status';b.innerHTML='<i></i>API';host.insertBefore(b,host.firstChild)}}
  function addAuthModal(){if($('#authModal'))return;const d=document.createElement('div');d.className='modal-backdrop';d.id='authModal';d.innerHTML=`<div class="modal auth-modal"><header class="modal-head"><div><h2>Entrar no BetSocial</h2><small>Conecte o frontend à API do Sprint 5</small></div><button class="close-modal" id="closeAuth">×</button></header><form class="auth-form" id="authForm"><label>E-mail<input id="authEmail" type="email" value="matheus@betsocial.local" required></label><label>Senha<input id="authPassword" type="password" value="betsocial123" required></label><div class="auth-demo">Conta demo: <b>matheus@betsocial.local</b> / <b>betsocial123</b></div><button class="publish-btn" type="submit">Entrar</button><button class="outline-btn" type="button" id="logoutBtn">Sair da conta atual</button></form></div>`;document.body.appendChild(d);$('#closeAuth').onclick=()=>d.classList.remove('open');$('#authForm').onsubmit=async e=>{e.preventDefault();try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('#authEmail').value,password:$('#authPassword').value})});token=x.token;localStorage.setItem(TOKEN_KEY,token);d.classList.remove('open');toast('Login realizado');syncAll()}catch(err){toast(err.message)}};$('#logoutBtn').onclick=async()=>{try{await api('/auth/logout',{method:'POST'})}catch(e){}token=null;localStorage.removeItem(TOKEN_KEY);toast('Sessão encerrada');d.classList.remove('open')}}
  function addLoginButton(){const chip=$('.profile-chip');if(!chip||chip.dataset.s5)return;chip.dataset.s5='1';chip.addEventListener('dblclick',()=>$('#authModal').classList.add('open'));chip.title='Duplo clique para autenticar na API'}
  function formatDate(v){const d=new Date(v),mins=Math.max(1,Math.floor((Date.now()-d)/60000));return mins<60?`há ${mins} min`:`há ${Math.floor(mins/60)} h`}
  function renderServerPosts(posts){const feed=$('.feed');if(!feed)return;document.querySelectorAll('.server-post').forEach(x=>x.remove());const tabs=$('.feed-tabs');posts.slice(0,8).forEach(p=>{const a=document.createElement('article');a.className='post card server-post';a.dataset.id=p.id;a.innerHTML=`<header class="post-header"><span class="avatar avatar-purple">${esc((p.author||'U')[0])}</span><div class="post-author"><b>${esc(p.author)} <span class="verified">✓</span></b><small>${esc(p.handle||'')} · ${formatDate(p.createdAt)}</small></div><span class="api-badge">API</span></header><p class="post-text">${esc(p.text||'')}</p><div class="bet-card"><div class="bet-top"><span>BET SOCIAL</span><span class="status">API</span></div><div class="bet-grid"><div><small>MERCADO</small><b>${esc(p.market)}</b></div><div><small>ODD</small><strong class="odd">${Number(p.odd||0).toFixed(2)}</strong></div><div><small>STAKE</small><b>${esc(p.stake)}%</b></div><div><small>CONFIANÇA</small><b class="confidence">${esc(p.confidence)}/10</b></div></div></div><footer class="post-footer"><button class="api-like">♥ <span>${p.likes||0}</span></button><button class="api-comment">◯ <span>${p.comments||0}</span></button></footer>`;tabs?.insertAdjacentElement('afterend',a)});bindServerActions()}
  function bindServerActions(){document.querySelectorAll('.api-like').forEach(b=>b.onclick=async()=>{if(!token)return $('#authModal').classList.add('open');try{const id=b.closest('.server-post').dataset.id;const x=await api(`/posts/${id}/like`,{method:'POST'});b.querySelector('span').textContent=x.likes;toast('Curtida sincronizada no servidor')}catch(e){toast(e.message)}});document.querySelectorAll('.api-comment').forEach(b=>b.onclick=async()=>{if(!token)return $('#authModal').classList.add('open');const text=prompt('Comentário');if(!text?.trim())return;try{const id=b.closest('.server-post').dataset.id;const x=await api(`/posts/${id}/comments`,{method:'POST',body:JSON.stringify({text})});b.querySelector('span').textContent=x.comments;toast('Comentário salvo no servidor')}catch(e){toast(e.message)}})}
  async function syncAll(){if(!token){return}try{const me=await api('/auth/me');document.querySelectorAll('.profile-copy b').forEach(x=>x.textContent=me.user.name);document.querySelectorAll('.profile-copy small').forEach(x=>x.textContent=me.user.handle);const posts=await api('/posts');renderServerPosts(posts.posts);const ns=await api('/notifications');const btn=$('[data-action="notificações"]');if(btn){let dot=btn.querySelector('i');if(!dot){dot=document.createElement('i');btn.appendChild(dot)}dot.style.display=ns.notifications.some(n=>!n.read)?'block':'none'}}catch(e){if(/autenticado|login/i.test(e.message)){token=null;localStorage.removeItem(TOKEN_KEY)}}}
  async function publishToApi(){if(!token)return;try{const state=BetSocialStore.get();const p=state.posts?.[0];if(!p)return;const marker='betsocial_api_'+p.id;if(localStorage.getItem(marker))return;await api('/posts',{method:'POST',body:JSON.stringify(p)});localStorage.setItem(marker,'1');toast('Publicação sincronizada com o backend');syncAll()}catch(e){toast('Não foi possível sincronizar: '+e.message)}}
  function hookWizard(){const b=$('#nextStep');if(!b)return;b.addEventListener('click',()=>{setTimeout(()=>{if(document.querySelector('.wizard-page.active')?.dataset.page==='1' && !token){};if(document.querySelector('.wizard-page.active')?.dataset.page==='5')publishToApi()},300)})}
  addStatus();addAuthModal();addLoginButton();health();syncAll();hookWizard();setInterval(health,15000);
  window.BetSocialAPI={login:()=>$('#authModal').classList.add('open'),syncAll};
})();
