'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { User } from '@/types';

export function AuthModal({ open, initialMode='login', onClose, onAuthenticated }:{open:boolean;initialMode?:'login'|'register';onClose:()=>void;onAuthenticated:(user:User)=>void}){
 const [mode,setMode]=useState<'login'|'register'>(initialMode); useEffect(()=>{if(open)setMode(initialMode)},[open,initialMode]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 if(!open)return null;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{let data:any;if(mode==='login'){data=await api('/api/auth/login',{method:'POST',body:JSON.stringify({identity:String(fd.get('identity')),password:String(fd.get('password'))})});}else{if(fd.get('password')!==fd.get('confirm'))throw new Error('As senhas não coincidem.');data=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:String(fd.get('name')),handle:String(fd.get('handle')),email:String(fd.get('email')),password:String(fd.get('password'))})});}onAuthenticated(data.user);window.dispatchEvent(new Event('gambly:auth-refresh'));}catch(err){setError(err instanceof Error?err.message:'Não foi possível concluir.')}finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="auth-modal"><button className="modal-close" onClick={onClose}>×</button><img src="/assets/gambly-wordmark.png" className="auth-wordmark" alt="GAMBLY"/><h1>{mode==='login'?'Bem-vindo de volta':'Crie sua conta'}</h1><p>{mode==='login'?'Entre para acompanhar suas análises.':'Faça parte da comunidade GAMBLY.'}</p><form onSubmit={submit}>{mode==='register'&&<><label>Nome<input name="name" required placeholder="Seu nome"/></label><label>Usuário<input name="handle" required placeholder="seuusuario"/></label><label>E-mail<input name="email" type="email" required placeholder="voce@email.com"/></label></>} {mode==='login'&&<label>E-mail ou usuário<input name="identity" required placeholder="Digite seu e-mail ou usuário"/></label>}<label>Senha<input name="password" type="password" required placeholder="••••••••"/></label>{mode==='register'&&<label>Confirmar senha<input name="confirm" type="password" required placeholder="••••••••"/></label>}{error&&<div className="form-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':'Criar conta'}</button></form><button className="switch-auth" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Não tem uma conta? Cadastre-se':'Já tem uma conta? Entrar'}</button></section></div>
}
