'use client';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { createPost, createPrediction, createPredictionSlip, getEventPlayers, getEvents } from '@/lib/api';
import type { Event, PlayerStat, User } from '@/types';

type EventOption = Event & {homeTeam:string;awayTeam:string;league:string;country?:string};
type Leg = { eventId:string; type:string; selection:string; playerName?:string; playerId?:string|number; odds?:number };
type Mode = 'analysis'|'game'|'image'|'prediction';
const marketOptions=[['winner','Vencedor'],['draw','Empate'],['double_chance','Dupla chance'],['first_half_winner','Vencedor 1º tempo'],['over_under','Gols — Mais/Menos'],['both_teams_score','Ambas marcam'],['corners_over_under','Escanteios — Mais/Menos'],['cards_over_under','Cartões — Mais/Menos'],['shots_on_target_over_under','Chutes no alvo — Mais/Menos'],['total_shots_over_under','Chutes totais — Mais/Menos'],['offsides_over_under','Impedimentos — Mais/Menos'],['fouls_over_under','Faltas — Mais/Menos'],['team_goals_over_under','Gols da equipe — Mais/Menos'],['exact_score','Placar exato'],['player_anytime_score','Jogador marca a qualquer momento'],['player_goals','Gols do jogador — Mais/Menos'],['player_assists','Assistências do jogador — Mais/Menos'],['player_shots_on_target','Chutes no alvo do jogador — Mais/Menos'],['player_shots','Chutes do jogador — Mais/Menos'],['player_to_be_booked','Jogador recebe cartão'],['player_cards','Cartões do jogador — Mais/Menos'],['player_red_cards','Cartão vermelho do jogador'],['player_passes','Passes do jogador — Mais/Menos'],['player_tackles','Desarmes do jogador — Mais/Menos'],['player_fouls','Faltas do jogador — Mais/Menos']] as [string,string][];

export function ComposerModal({open,onClose,initialMode='analysis',initialEventId='',user}:{open:boolean;onClose:()=>void;initialMode?:Mode;initialEventId?:string;user:User|null}){
 const [mode,setMode]=useState<Mode>(initialMode),[events,setEvents]=useState<EventOption[]>([]),[eventId,setEventId]=useState(initialEventId),[eventSearch,setEventSearch]=useState('');
 const [type,setType]=useState('winner'),[selection,setSelection]=useState(''),[playerName,setPlayerName]=useState(''),[playerId,setPlayerId]=useState<string|number|undefined>(),[players,setPlayers]=useState<PlayerStat[]>([]),[playerSearch,setPlayerSearch]=useState(''),[odds,setOdds]=useState('2.10');
 const [text,setText]=useState(''),[multi,setMulti]=useState(false),[legs,setLegs]=useState<Leg[]>([]),[title,setTitle]=useState('Palpite múltiplo'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[image,setImage]=useState(''),[imageName,setImageName]=useState('');
 const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!open)return;setMode(initialMode);setEventId(initialEventId);setError('');setLegs([]);setPlayerName('');setPlayerId(undefined);setPlayers([]);setPlayerSearch('');setMulti(false);setTitle('Palpite múltiplo');setText('');setImage('');setImageName('');setEventSearch('');getEvents().then(r=>{const list=r.events as EventOption[];setEvents(list);if(initialEventId)setEventId(initialEventId);else if(initialMode!=='analysis')setEventId(list.find(e=>e.status==='live')?.id||list[0]?.id||'')}).catch(()=>setEvents([]));},[open,initialMode,initialEventId]);
 const selected=events.find(e=>e.id===eventId);
 useEffect(()=>{if(!selected||!type.startsWith('player_')){setPlayers([]);return}getEventPlayers(selected.id).then(r=>setPlayers(r.players||[])).catch(()=>setPlayers([]))},[selected?.id,type]);
 const filteredEvents=useMemo(()=>{const q=eventSearch.trim().toLowerCase();return events.filter(e=>!q||`${e.homeTeam} ${e.awayTeam} ${e.league} ${e.country||''}`.toLowerCase().includes(q)).slice(0,20)},[events,eventSearch]);
 const filteredPlayers=useMemo(()=>{const q=playerSearch.trim().toLowerCase();return players.filter(p=>!q||p.name.toLowerCase().includes(q)).slice(0,30)},[players,playerSearch]);
 const selections=useMemo(()=>{if(!selected)return[];if(type.startsWith('player_')){if(!playerName)return[];if(['player_anytime_score','player_to_be_booked'].includes(type))return[playerName];return['0.5','1.5','2.5','3.5'].flatMap(x=>[`Over ${x}`,`Under ${x}`]).map(x=>`${playerName} ${x}`)}if(type==='winner')return[selected.homeTeam,selected.awayTeam];if(type==='draw')return['Empate'];if(type==='double_chance')return['1X','X2','12'];if(type==='first_half_winner')return['Casa','Empate','Fora'];if(type==='both_teams_score')return['Sim','Não'];if(type==='exact_score')return['1-0','2-0','2-1','1-1','0-1','0-2','1-2'];const lines=type==='corners_over_under'?['4.5','5.5','6.5','7.5','8.5','9.5','10.5','11.5']:type==='cards_over_under'?['1.5','2.5','3.5','4.5','5.5','6.5']:type==='shots_on_target_over_under'?['2.5','3.5','4.5','5.5','6.5','7.5']:type==='total_shots_over_under'?['15.5','17.5','19.5','21.5','23.5','25.5']:type==='offsides_over_under'?['1.5','2.5','3.5','4.5','5.5']:type==='fouls_over_under'?['15.5','19.5','23.5','27.5','31.5']:type==='team_goals_over_under'?['0.5','1.5','2.5','3.5']:['0.5','1.5','2.5','3.5','4.5'];if(type==='team_goals_over_under')return lines.flatMap(x=>[`Casa Over ${x}`,`Casa Under ${x}`,`Fora Over ${x}`,`Fora Under ${x}`]);return lines.flatMap(x=>[`Over ${x}`,`Under ${x}`]);},[selected,type,playerName]);
 const selectPlayer=(p:PlayerStat)=>{setPlayerName(p.name);setPlayerId(p.id??undefined);setPlayerSearch(p.name);setSelection('')};
 const resetMarket=()=>{setSelection('');setPlayerName('');setPlayerId(undefined);setPlayerSearch('')};
 const addLeg=()=>{if(!eventId||!selection)return setError('Escolha o jogo e a seleção.');if(legs.some(x=>x.eventId===eventId))return setError('Esse jogo já está no palpite múltiplo.');const n=Number(odds);if(!Number.isFinite(n)||n<=0)return setError('Informe uma odd válida.');if(legs.length>=10)return setError('O palpite múltiplo aceita no máximo 10 seleções.');setLegs([...legs,{eventId,type,selection,playerName:playerName||undefined,playerId,odds:n}]);setSelection('');resetMarket();setError('')};
 const removeLeg=(id:string)=>setLegs(legs.filter(x=>x.eventId!==id));
 const changeMode=(next:Mode)=>{setMode(next);setError('');if(next==='image')setTimeout(()=>fileRef.current?.click(),80)};
 const handleFile=(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/'))return setError('Escolha uma imagem JPG, PNG ou WEBP.');if(file.size>2.5*1024*1024)return setError('A imagem precisa ter no máximo 2,5 MB.');const reader=new FileReader();reader.onload=()=>{setImage(String(reader.result||''));setImageName(file.name);setError('')};reader.readAsDataURL(file)};
 async function submit(e:FormEvent){e.preventDefault();if(!user)return setError('Entre na sua conta para publicar.');setBusy(true);setError('');try{let createdPost=null;if(mode==='image'){if(!image)throw new Error('Escolha uma imagem antes de publicar.');createdPost=(await createPost({type:'Imagem',title:'Foto da comunidade',text:text.trim(),image})).post}else if(mode==='game'){if(!eventId)throw new Error('Escolha um jogo.');if(!text.trim())throw new Error('Escreva algo sobre o jogo.');createdPost=(await createPost({type:'Jogo',title:`${selected?.homeTeam||'Casa'} × ${selected?.awayTeam||'Fora'}`,text:text.trim(),eventId})).post}else if(mode==='analysis'){if(!text.trim())throw new Error('Escreva sua análise antes de publicar.');createdPost=(await createPost({type:'Análise',title:'Nova análise',text:text.trim(),eventId:eventId||undefined})).post}else if(multi){const all=selection?[...legs,{eventId,type,selection,playerName:playerName||undefined,playerId,odds:Number(odds)}]:legs;if(all.length<2)throw new Error('Adicione pelo menos 2 seleções ao palpite múltiplo.');if(all.some(x=>!x.eventId||!x.selection||!Number.isFinite(Number(x.odds))))throw new Error('Revise as seleções e odds do múltiplo.');const r=await createPredictionSlip({title,items:all});createdPost=(await createPost({type:'Palpite',title:`${title} — ${all.length} seleções`,text:text.trim()||'Meu palpite múltiplo para a comunidade.',market:'Múltiplo',odd:Number(all.reduce((a,x)=>a*Number(x.odds||1),1).toFixed(2)),predictionId:r.predictions[0]?.id,slipId:r.slip.id,eventId:all[0]?.eventId})).post}else{if(!eventId||!selection)throw new Error('Escolha o jogo e a seleção do palpite.');if(type.startsWith('player_')&&!playerName)throw new Error('Escolha um jogador.');const n=Number(odds);if(!Number.isFinite(n)||n<=0)throw new Error('Informe uma odd válida.');const r=await createPrediction({eventId,type,selection,playerName:playerName||undefined,playerId,odds:n});createdPost=(await createPost({type:'Palpite',title:`Palpite: ${selection}`,text:text.trim()||`Meu palpite para ${selected?.homeTeam} × ${selected?.awayTeam}.`,market:type,odd:n,predictionId:r.prediction.id,eventId})).post}if(createdPost)window.dispatchEvent(new CustomEvent('gambly:post-created',{detail:createdPost}));onClose()}catch(err){setError(err instanceof Error?err.message:'Não foi possível publicar.')}finally{setBusy(false)}}
 if(!open)return null;
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="composer-modal composer-pro"><button className="modal-close" onClick={onClose}>×</button><div className="composer-heading"><div><span className="eyebrow">NOVA PUBLICAÇÃO</span><h2>{mode==='prediction'?'Criar palpite':mode==='image'?'Publicar foto':mode==='game'?'Compartilhar jogo':'Criar análise'}</h2><p>Escolha o formato e conecte sua publicação ao jogo certo.</p></div>{user&&<span className="composer-user">{user.avatar?<img src={user.avatar} alt=""/>:user.name.slice(0,1).toUpperCase()}</span>}</div>
  <div className="composer-mode-tabs">{([['analysis','📊 Análise'],['prediction','🎯 Palpite'],['game','⚽ Jogo'],['image','📷 Foto']] as [Mode,string][]).map(([m,label])=><button type="button" key={m} className={mode===m?'active':''} onClick={()=>changeMode(m)}>{label}</button>)}</div>
  {error&&<div className="auth-error">{error}</div>}
  <form onSubmit={submit}>
   {mode!=='image'&&<div className="event-picker"><label>Vincular jogo {mode==='analysis'&&<small>opcional</small>}</label><div className="event-search">🔎<input value={eventSearch} onChange={e=>setEventSearch(e.target.value)} placeholder="Pesquisar time, campeonato ou jogo..."/></div>{selected&&<button type="button" className="selected-event" onClick={()=>{setEventId('');setEventSearch('')}}><span><b>{selected.homeTeam} × {selected.awayTeam}</b><small>{selected.league} · {selected.status==='live'?'🔴 AO VIVO':new Date(selected.startTime).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></span><i>×</i></button>}<div className="event-results">{!selected&&filteredEvents.map(e=><button type="button" key={e.id} onClick={()=>{setEventId(e.id);setEventSearch('');resetMarket()}}><span><b>{e.homeTeam} × {e.awayTeam}</b><small>{e.league} · {e.status==='live'?'🔴 AO VIVO':new Date(e.startTime).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></span><strong>{e.homeScore!=null?`${e.homeScore} × ${e.awayScore}`:''}</strong></button>)}</div></div>}
   {mode==='analysis'&&<><label>O que você está vendo?<textarea value={text} onChange={e=>setText(e.target.value.slice(0,1000))} placeholder="Compartilhe sua leitura, contexto ou análise..." rows={6} autoFocus/></label><div className="helper-row"><span>💡 Uma boa análise explica o porquê.</span><b>{text.length}/1000</b></div></>}
   {mode==='game'&&<label>Comentário<textarea value={text} onChange={e=>setText(e.target.value.slice(0,1000))} placeholder="O que você espera desse jogo?" rows={5}/></label>}
   {mode==='image'&&<><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>handleFile(e.target.files?.[0])}/><button type="button" className="image-dropzone" onClick={()=>fileRef.current?.click()}>{image?<img src={image} alt="Prévia"/>:<><span>📷</span><strong>Escolha uma foto</strong><small>JPG, PNG ou WEBP · até 2,5 MB</small></>}</button>{image&&<div className="image-file-row"><span>{imageName}</span><button type="button" onClick={()=>{setImage('');setImageName('')}}>Remover</button></div>}<label>Legenda<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Adicione uma legenda..." rows={4}/></label></>}
   {mode==='prediction'&&<>{!selected?<div className="composer-tip">Escolha um jogo acima para liberar os mercados.</div>:<><div className="format-switch"><button type="button" className={!multi?'active':''} onClick={()=>setMulti(false)}>Palpite simples</button><button type="button" className={multi?'active':''} onClick={()=>setMulti(true)}>Palpite múltiplo</button></div>{multi&&<label>Título do múltiplo<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120}/></label>}<div className="form-grid"><label>Mercado<select value={type} onChange={e=>{setType(e.target.value);resetMarket()}}>{marketOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Seleção<select value={selection} onChange={e=>setSelection(e.target.value)}><option value="">Selecione</option>{selections.map(x=><option key={x}>{x}</option>)}</select></label></div>{type.startsWith('player_')&&<div className="player-picker"><label>Jogador</label><div className="event-search">🔎<input value={playerSearch} onChange={e=>setPlayerSearch(e.target.value)} placeholder="Pesquisar jogador..."/></div>{playerName&&<div className="selected-event"><span><b>{playerName}</b><small>Jogador selecionado</small></span><button type="button" onClick={resetMarket}>×</button></div>}<div className="player-results">{!playerName&&filteredPlayers.map(p=><button type="button" key={`${p.id}-${p.name}`} onClick={()=>selectPlayer(p)}><span><b>{p.name}</b><small>{p.goals??0} G · {p.assists??0} A · {p.shots??0} chutes</small></span></button>)}{!players.length&&<small className="muted-note">Jogadores ainda não disponíveis para esta partida.</small>}</div></div>}<div className="form-grid"><label>Odd<input value={odds} onChange={e=>setOdds(e.target.value)} inputMode="decimal"/></label><label>Comentário<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Por que você acredita nesse palpite?" rows={3}/></label></div>{multi&&<><button type="button" className="outline-btn add-leg-btn" onClick={addLeg}>＋ Adicionar seleção ao múltiplo</button><div className="slip-legs">{legs.map((leg,i)=>{const ev=events.find(x=>x.id===leg.eventId);return <div className="slip-leg" key={leg.eventId}><span className="leg-number">{i+1}</span><span><b>{ev?.homeTeam||'Casa'} × {ev?.awayTeam||'Fora'}</b><small>{leg.selection} · odd {Number(leg.odds).toFixed(2)}</small></span><button type="button" onClick={()=>removeLeg(leg.eventId)}>×</button></div>})}</div><small className="slip-count">{legs.length} seleção(ões) adicionada(s) · máximo 10</small></>}</>}</>}
   <button className="auth-submit composer-submit" disabled={busy||!user||((mode==='game'||mode==='prediction')&&!eventId)}>{busy?'Publicando...':mode==='prediction'?(multi?'Publicar múltiplo':'Publicar palpite'):'Publicar no GAMBLY'}</button>{!user&&<small className="login-hint">Entre ou crie sua conta para publicar.</small>}
  </form>
 </section></div>
}
