'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { getLiveGames } from '@/lib/api';
import type { LiveGame } from '@/types';
function Logo({src,name}:{src?:string;name:string}){return <span className="live-logo">{src?<img src={src} alt="" loading="lazy" width={30} height={30}/>:name.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span>}
function groupByLeague(items:LiveGame[]){const m=new Map<string,LiveGame[]>();items.forEach(g=>{const k=g.league||'Futebol';if(!m.has(k))m.set(k,[]);m.get(k)!.push(g)});return [...m.entries()]}
export function LiveCenter(){
 const [games,setGames]=useState<LiveGame[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[sport,setSport]=useState('all'),[status,setStatus]=useState('live'),[last,setLast]=useState('');
 const load=async()=>{try{setError('');const d=await getLiveGames({search:search.trim(),sport:sport==='all'?'':sport,status});setGames(d.games||[]);setLast(d.updatedAt||new Date().toISOString())}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os jogos.')}finally{setLoading(false)}};
 useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>window.clearInterval(t)},[sport,status]);
 useEffect(()=>{const t=window.setTimeout(load,350);return()=>window.clearTimeout(t)},[search]);
 const counts=useMemo(()=>({all:games.length,live:games.filter(g=>g.status==='live').length,scheduled:games.filter(g=>g.status==='scheduled').length,finished:games.filter(g=>g.status==='finished').length}),[games]);
 const groups=useMemo(()=>groupByLeague(games),[games]);
 return <section className="live-center sprint32-live"><div className="live32-head"><div><span className="eyebrow">LIVE CENTER 2.0</span><h1>🔴 Ao Vivo</h1><p>Todos os jogos, organizados por esporte e campeonato.</p></div><div className="live32-total"><b>{games.length}</b><span>partidas</span></div></div>
 <div className="live32-sports card"><button className={sport==='all'?'active':''} onClick={()=>setSport('all')}>◉ Todos</button><button className={sport==='football'?'active':''} onClick={()=>setSport('football')}>⚽ Futebol</button><button className={sport==='basketball'?'active':''} onClick={()=>setSport('basketball')}>🏀 Basquete</button><button className={sport==='tennis'?'active':''} onClick={()=>setSport('tennis')}>🎾 Tênis</button></div>
 <div className="live32-toolbar card"><div className="live-search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar time, campeonato..."/></div><div className="live32-status"><button className={status==='live'?'active':''} onClick={()=>setStatus('live')}>🔴 Ao vivo <b>{counts.live}</b></button><button className={status==='scheduled'?'active':''} onClick={()=>setStatus('scheduled')}>🕐 Próximos <b>{counts.scheduled}</b></button><button className={status==='finished'?'active':''} onClick={()=>setStatus('finished')}>✓ Encerrados <b>{counts.finished}</b></button><button className={status==='all'?'active':''} onClick={()=>setStatus('all')}>Todos <b>{counts.all}</b></button></div></div>
 {last&&<div className="live-updated">Atualizado {new Date(last).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})} · atualização somente nesta página</div>}
 {error&&<div className="card live-error">⚠️ {error}<button onClick={load}>Tentar novamente</button></div>}
 {loading?<div className="live-skeletons">{[1,2,3].map(x=><div className="card live-skeleton" key={x}/>)}</div>:!groups.length?<div className="card live-empty"><div>🏟️</div><h2>Nenhuma partida encontrada</h2><p>Tente o filtro Todos ou aguarde a sincronização do provedor esportivo.</p></div>:groups.map(([league,rows])=><div className="live32-league" key={league}><div className="live32-league-head"><div><span>🏆</span><b>{league}</b></div><em>{rows.length} jogo{rows.length===1?'':'s'}</em></div><div className="live32-list">{rows.map(g=><Link href={`/live/${g.id}`} className="live32-game card" key={g.id}><div className="live32-game-meta"><span>{g.country||'Internacional'}</span><b>{g.status==='live'?(g.minute!=null?`${g.minute}'`:'LIVE'):g.status==='finished'?'FT':g.startTime?new Date(g.startTime).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'—'}</b></div><div className="live32-teams"><div><Logo src={g.homeLogo} name={g.home}/><b>{g.home}</b><strong>{g.homeScore??'—'}</strong></div><div><Logo src={g.awayLogo} name={g.away}/><b>{g.away}</b><strong>{g.awayScore??'—'}</strong></div></div><div className="live32-foot"><span className={g.status==='live'?'live-green':''}>{g.status==='live'?'🔴 AO VIVO':g.status==='finished'?'✓ Encerrado':'🕐 Próximo'}</span><span>Estatísticas →</span></div></Link>)}</div></div>)}
 </section>
}
