/* BetSocial v0.11 — rede, perfil real, feed personalizado e chat por conversa */
(()=>{
 const api=window.BetSocialV8?.api || window.BetSocialV7?.api; if(!api)return;
 const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const toast=v=>{const t=$('#toast');if(t){t.textContent=v;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}};
 async function profile(){try{const d=await api('/profile');const u=d.user;document.querySelectorAll('.profile-chip .profile-copy b,.profile-modal .profile-row-info h2,.profile-card h2').forEach(x=>x.textContent=u.name);document.querySelectorAll('.profile-chip .profile-copy small,.profile-modal .profile-row-info small').forEach(x=>x.textContent=u.handle+(x.closest('.profile-row-info')?' · Membro desde 2026':''));const bio=$('.profile-bio');if(bio)bio.textContent=u.bio||'';return u}catch(e){return null}}
 async function network(){try{const d=await api('/network');window.BetSocialNetwork=d;const list=document.querySelector('.follow-list');if(list)list.innerHTML=d.users.slice(0,20).map(u=>`<div class="follow-card"><span class="avatar avatar-purple avatar-xs">${esc((u.name||'?')[0])}</span><div><b>${esc(u.name)}</b><small>${esc(u.handle)}</small></div><button class="outline-btn follow-live" data-user-id="${u.id}">${u.following?'Seguindo':'Seguir'}</button></div>`).join('')||'<div class="empty-state">Nenhum usuário encontrado.</div>';return d}catch(e){return null}}
 document.addEventListener('click',async e=>{const b=e.target.closest('.follow-live');if(!b)return;try{const d=await api('/users/'+b.dataset.userId+'/follow',{method:'POST'});b.textContent=d.following?'Seguindo':'Seguir';toast(d.following?'Você começou a seguir este usuário.':'Você deixou de seguir este usuário.');network()}catch(err){toast(err.message)}});
 async function openConversation(name){const users=(await network())?.users||[];const target=users.find(u=>u.name===name)||users[0];if(!target)return toast('Usuário não encontrado.');$('#conversationTitle').textContent=target.name;const d=await api('/messages');const msgs=d.messages.filter(m=>m.from===target.id||m.to===target.id);const body=$('#conversationBody');if(body)body.innerHTML=msgs.map(m=>`<div class="bubble-row ${m.to===target.id?'me':''}"><div class="bubble">${esc(m.text)}</div></div>`).join('')||'<div class="empty-state">Comece a conversa.</div>';await api('/messages/read',{method:'POST',body:JSON.stringify({from:target.id})}).catch(()=>{});document.querySelector('#conversationModal')?.classList.add('open');window.BetSocialConversationTarget=target.id;body?.scrollTo(0,99999)}
 document.querySelectorAll('.message-preview').forEach(el=>el.addEventListener('click',()=>openConversation(el.dataset.conversation)));
 const send=$('#sendMessage');if(send){send.onclick=async()=>{const text=$('#messageInput')?.value.trim(),to=window.BetSocialConversationTarget;if(!text||!to)return;try{const d=await api('/messages',{method:'POST',body:JSON.stringify({to,text})});const row=document.createElement('div');row.className='bubble-row me';row.innerHTML='<div class="bubble"></div>';row.firstElementChild.textContent=d.message.text;$('#conversationBody')?.appendChild(row);$('#messageInput').value='';$('#conversationBody')?.scrollTo(0,99999)}catch(e){toast(e.message)}}}
 window.BetSocialV9={profile,network,openConversation};profile();
})();
